baseURL: "https://uxui.cat"

title: UX/UI Barcelona

sectionPagesMenu: main

taxonomies:
  topics: topics
  author: authors
  source: sources

markup:
  goldmark:
    renderer:
      unsafe: true

enableGitInfo: true
