baseURL: "https://uxui.cat"

title: UX/UI Barcelona

params:
  title: UX/UI Barcelona
  description: Learn User Experience and Interaction Design in Barcelona

taxonomies:
  topics: topics
  author: authors
  source: sources

related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: topics
      weight: 100
    - name: title
      weight: 80
    - name: authors
      weight: 80
    - name: sources
      weight: 20
    - name: date
      weight: 10


markup:
  goldmark:
    renderer:
      unsafe: true

enableGitInfo: true

frontmatter:
  date: ["date", "publishDate", "lastmod", ":git"]
  lastmod: ["lastmod", ":git", ":default"]
